spring:
  application:
    # 服务名称
    name: spring-cloud-eureka-server

server:
  # 端口号
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      # 双服务中心
      defaultZone: http://eureka2:8762/eureka/
    # 当前服务是否注册到eureka
    register-with-eureka: true
    # 表示eurekaServer是否获取服务地址
    fetch-registry: true
  server:
    # 可以设置改参数值为false，以确保注册中心将不可用的实例删除
    enableSelfPreservation: false
#spring.security.basic.enabled=true
#spring.security.user.name=root
#spring.security.user.password=123456